resolver: lts-7.16
packages:
- '.'
- location:
    git: https://github.com/bscarlet/llvm-general.git
    commit: ec1ad5bd2112e7f64dbb43441b5e2075cf6ad8e7
  subdirs:
    - llvm-general-pure
    - llvm-general
  extra-dep: true
